import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps, NextPage } from "next";
import { ProductProps } from "@/core/domain/entities/product";
import Link from "next/link";
import { remoteListProductsUseCase } from "@/core/main/factories/use-cases/product";
import { useCartContext } from "@/hooks/use-cart";

const inter = Inter({ subsets: ["latin"] });

type HomeProps = {
  products: ProductProps[];
};

const Home: NextPage<HomeProps> = ({ products }) => {
  const { state } = useCartContext();

  const clearCart = () => {
    state.cart.clear();
  };

  return (
    <>
      <Head>
        <title>E-commerce Clean Architecture</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header>
          <button onClick={clearCart}>Limpar carrinho</button>
          <h2 className={inter.className}>E-commerce Clean Architecture</h2>
        </header>
        <div>
          <ul>
            {products.map((product) => (
              <li key={product.id}>
                Nome: {product.name} | value: {product.price} |{" "}
                <Link href={`/products/${product.id}`}>Ver</Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const products = await remoteListProductsUseCase.execute();

  return {
    props: {
      products: products,
    },
  };
};
